### ISSUE TITLE
Mute toggle

### ISSUE THREAD

**Issue by bendavid** [ol-iver/denonavr#101]
It might be desirable in some cases to send a mute toggle command to the AVR, to be less dependent on state.

This seems not possible directly using the http or telnet protocol, but can still be accomplished by sending remote codes over http.

For the main zone on the AVR-X4400H this works with
"/goform/formiPhoneAppDirect.xml?RCKSK0410370"

For zone 2 this should be 
RCKSK0430370

and for zone 3 
RCKSK0450370

Some older denon list of IR codes which still seems to be applicable to current models:
http://www.denon-hifi.nl/uk/product/hometheater/avreceivers/avr3313?docname=AVR3313_IR_CODE_V01.pdf

**Comment by JPHutchins** [comment]
Wow.  This code list is extensive and I can confirm that they are working with AVR-X1500H.  I would like to refactor the constants anyway so I will begin cataloging some of these and running them in a test environment along with Home Assistant.  

Even better, the newer XML API was not backwards compatible but I would suppose that these codes are.

The only downside that I can see is that Denon is simply returning a 200 response when it receives a command in this form, whether the command is gibberish or not.  This is different than some of the other /formiPhoneAppDirect.xml? based commands which do return XML confirming the new state.

Anyone have more thoughts?

Cheers,
J.P.

**Comment by bendavid** [comment]
Some more reference on this is here
https://ca.denon.com/ca/product/hometheater/receivers/avrx4400h?docname=AVR-X6400H_X4400H_X3400H_X2400H_X1400H_S930H_S730H_PROTOCOL_V01.xlsx

I got the hint from the "Extension Command" page.  I assume it's already known that ~any of the telnet commands should work when passed to /goform/formiPhoneAppDirect.xml

**Comment by JPHutchins** [comment]
I have submitted PR that includes all of the RCKSK codes from the document and a demo of the mute_toggle() method, tested working on my X1500H.  

PR: https://github.com/scarface-4711/denonavr/pull/103
Branch if you want to clone and test/help: https://github.com/JPHutchins/denonavr/tree/3313-IR

**Comment by JPHutchins** [comment]
Actually I was unable to get some of the telnet commands to work via that endpoint which is why I was sniffing the app and implementing an XML based API: https://github.com/JPHutchins/denonavr/tree/xml-commands

edit: LMAO I did not know you could put a space at the end of a POST like this:
`/goform/formiPhoneAppDirect.xml?PSDYNVOL HEV`
The main advantage to this would be readability - unfortunately I am not getting any response body.

**Comment by bendavid** [comment]
Another interesting feature of the xml API is that it looks like it has at least limited support for http SUBSCRIBE/NOTIFY such that one can update the avr state at least partly with asynchronous callbacks rather than polling.

**Comment by JPHutchins** [comment]
I noticed that but have not played with it.   Haven't had a chance to explore, but I think something is causing some slow behavior in this HA integration.

**Comment by bendavid** [comment]
Did you already think about what changes are needed to the HomeAssistant api's in order to call arbitrary commands? (One could add a dedicated api call for the denonavr component, but since one may e encounter similar issues elsewhere, I wonder if it makes more sense to implement something generic at the media_player level.)

**Comment by bendavid** [comment]
https://github.com/home-assistant/home-assistant/pull/28280

**Comment by JPHutchins** [comment]
I think that this is a great idea and will subscribe to the PR to support your effort.  HA architecture is very careful.  Generally, they may want this implemented in this denonavr library so that it can be maintained outside of HA.

It is not immediately on my to-do list, but in my opinion their is very little overlap between a "media player" and a "receiver".  For this reason I believe that there should be a separate component for receivers as the media player component is already bogged down dealing with various streaming services, transport controls, etc.  Then media players would routed to receivers and displays as necessary to control power on/off volume control etc.

**Comment by bendavid** [comment]
Indeed there was some resistance to implementing this in the media_player domain, so I added a dedicated service rather.
https://github.com/home-assistant/home-assistant/pull/29295
