### ISSUE TITLE
Adding Python 2.7 Support

### ISSUE THREAD

**Issue by Ben-Mathews** [ol-iver/denonavr#128]
I'd like to use your package as part of an EventGhost plugin, but EventGhost is still on Python 2.7.  I made a small number of changes to enable backward compatibility with Python 2.7.  All of the unit tests still pass.

See Merge Request: [https://github.com/scarface-4711/denonavr/pull/127](https://github.com/scarface-4711/denonavr/pull/127)

BTW, my initial commit had a few formatting issues that houndci complained about.  I fixed those in subsequent commits but still see some evidence of houndci complaining about them in the pull request.

Thanks for sharing your awesome work!

**Comment by ol-iver** [comment]
hi @Ben-Mathews,
I'm glad to hear you like my work 😄 

Python 2.7 is end-of-life since 2020-01-01. I spend some thoughts and in the end I came to the conclusion not to make it compatible to python 2.7.
The number of parts in the code where python 2.7 and 3 are not compatible would increase over the time and I don't want to start this with the end-of-life fact in mind.

I don't know much about EventGhost and if it will be running on python 3 soon. If not you are welcome to use your fork of denonavr there.

**Comment by starkillerOG** [comment]
@Ben-Mathews I too started my programming with EventGhost and still use it today. I actually wrote my own python code to control a marantz receiver in EventGhost and that was basically my first experience with coding back in like 2008 or something.

I would highly recommend giving HomeAssistant a try, you will need something like a raspberry pi to eventually run it on (always available), but you can even try it out on windows.

If you like EventGhost to control your receiver, you are going to love HomeAssistant!

You can see a demo here: https://demo.home-assistant.io/#/lovelace/0
