### ISSUE TITLE
Add support for additional sound mode

### ISSUE THREAD

**Issue by morhimi** [ol-iver/denonavr#153]
Hi,
I have a Denon 3300X AVR, I'm seeing this warning during setup:

```
Logger: DenonAVR
Source: /usr/local/lib/python3.8/site-packages/denonavr/denonavr.py:1716
First occurred: 6:10:19 AM (1 occurrences)
Last logged: 6:10:19 AM

Not able to match sound mode: 'DOLBY DIGITAL + + NEURAL:X', returning raw sound mode.
```

Can you please add support for this mode?
Thanks...

**Comment by JPHutchins** [comment]
@starkillerOG Sorry I have been absent.  Are these the kinds of errors we can fix with the SSDP stuff we were exploring a few months ago?  Specifically, we ask the receiver for a list of all supported sound modes instead of trying to keep up.  A "GetSupportedSoundModes" endpoint?

For reference, some sample XML and "DIY methodology" is here - it ain't pretty folks! https://github.com/scarface-4711/denonavr/issues/117

Furthermore, I would like to do this for "commands" but IIRC we never found a command list in the SSDP?  And we're not confident of backwards compatibility?

**Comment by starkillerOG** [comment]
@morhimi what version of denonavr are you running?
In the latest version 'DOLBY DIGITAL + + NEURAL:X' is already included so it schould be able to match that sound mode....

**Comment by starkillerOG** [comment]
@JPHutchins I have searched far and wide but was never able to find a proper list of the supported sound modes in the denonavr xmls, also not in the SSDP stuff. However it would be greath if you could figure out a way to "GetSupportedSoundModes".
Note that we also need to map the sound mode reported to the sound modes that can be set, that is the main problem.

**Comment by morhimi** [comment]
> @morhimi what version of denonavr are you running?
> In the latest version 'DOLBY DIGITAL + + NEURAL:X' is already included so it schould be able to match that sound mode....

I was using the latest version of Home Assistant as of that date.
I don't see these messages anymore though

**Comment by morhimi** [comment]
closing as I don't see these errors anymore
