### ISSUE TITLE
Input function NET is not known 

### ISSUE THREAD

**Issue by stefsmeets** [ol-iver/denonavr#182]
Hi, I'm getting this error using denonavr in home assistant 2020.12.1 with a Marantz CR511. It occurs about every 10 seconds, so it is generating a lot of spam in my logbook. Usually it seems to happen when I'm running Spotify Connect (which seems to map to NET).

```
Logger: DenonAVR
Source: /usr/local/lib/python3.8/site-packages/denonavr/denonavr.py:610
First occurred: 26 december 2020 17:35:38 (109528 occurrences)
Last logged: 13:46:20
Input function NET is not known 
```

**Comment by ol-iver** [comment]
Could you please run this [script](https://github.com/scarface-4711/misc_python_tools/tree/master/denonavr) when your receiver is powered on and is playing Spotify and upload the xml files it generates? These include the responses of the endpoints our library could query.

The log spam should be fixed in the next update anyhow.
