### ISSUE TITLE
Change input to TV Audio or AUX is not working from HomeAssistant

### ISSUE THREAD

**Issue by outrun0506** [ol-iver/denonavr#20]
Hi,

For me switch to Input "Aux" and "TV Audio" is not working from HomeAssistant.
Every other Input works just fine.

My Denon is an X2000

I found this in your code:

```python
SOURCE_MAPPING = {"TV AUDIO": "TV", "iPod/USB": "USB/IPOD", "Bluetooth": "BT",
                  "Blu-ray": "BD", "CBL/SAT": "SAT/CBL", "NETWORK": "NET"}

CHANGE_INPUT_MAPPING = {"Internet Radio": "IRP", "Online Music": "NET",
                        "Media Player": "MPLAY", "Media Server": "SERVER",
                        "Spotify": "SPOTIFY", "Flickr": "FLICKR",
                        "Favorites": "FAVORITES"}
```

Do i have to rename my Inputs? My Inputs are all set to default naming.
Any Ideas?

BR

LUkas

**Comment by ol-iver** [comment]
that's strange, because according to the documentation of the IP interface your X2000 should be working as my X4100 and on my device it is working.
Renaming should not influence setting the input, because the library is designed to consider renamed input functions and display them with their renamed name.
You could check the following things:
- Is Zone2 or Zone3 set to input functions TV Audio or Aux? At my device it happens sometimes, that I'm not able to switch to a input function in MainZone when it is already set at another zone.
- Check if you can switch to the input function using the device URL directly in your browser ( http://[DEVICE_IP]/goform/formiPhoneAppDirect.xml?SITV or http://[DEVICE_IP]/goform/formiPhoneAppDirect.xml?SIAUX1 )
- Homeassistant 0.47 is not using the most current version of github, you mentioned in your quote. It will be included to version 0.48. But if you like you could test the new version by replacing the file [homedir of homeassistant user]/.homeassistant/deps/denonavr/denonavr.py with the one you find here in github.
- You could send me the XML files of your receiver. Maybe I find something which is different than expected. I created a little python script for it mentioned in this comment https://github.com/scarface-4711/denonavr/issues/8#issuecomment-304328307 . Ideally you run it when your receiver is online and switched to TV Audio and/or Aux

Btw. the mapping you quoted is not because of sources sources you might rename in the web interfaces. Unfortunately denon is using different names for the same input functions in different interfaces (like for device info, getting current input sources or setting them). The mapping is made so bring them together

**Comment by outrun0506** [comment]
Hi,

Thanks for helping on this.

I did an Update to HA 0.48 today.

No switching to TV AUDIO is working like a charm.
AUX is not working.

I've changed logging in HA to debug, here is the output:

```
2017-07-02 20:12:19 INFO (Thread-11) [homeassistant.components.media_player.denonavr] Denon receiver at host 192.168.0.150 initialized
2017-07-02 20:12:52 ERROR (Thread-1) [DenonAVR] No mapping for source MPLAY
2017-07-02 20:12:59 ERROR (Thread-6) [DenonAVR] No mapping for source MPLAY
2017-07-02 20:13:58 ERROR (Thread-9) [DenonAVR] No mapping for source AUX1
2017-07-02 20:14:05 ERROR (Thread-10) [DenonAVR] No mapping for source AUX1
2017-07-02 20:14:09 ERROR (Thread-11) [DenonAVR] No mapping for source AUX1
2017-07-02 20:14:20 ERROR (Thread-9) [DenonAVR] No mapping for source AUX1
2017-07-02 20:14:31 ERROR (Thread-3) [DenonAVR] No mapping for source AUX1
2017-07-02 20:14:42 ERROR (Thread-1) [DenonAVR] No mapping for source AUX1
2017-07-02 20:14:53 ERROR (Thread-6) [DenonAVR] No mapping for source AUX1
2017-07-02 20:14:54 ERROR (Thread-6) [DenonAVR] Host 192.168.0.150 returned malformed XML for: /goform/Deviceinfo.xml
2017-07-02 20:14:54 ERROR (Thread-6) [DenonAVR] Connection error: Receiver sources list empty. Please check if device is powered on.
2017-07-02 20:14:54 ERROR (Thread-6) [DenonAVR] Input function list for Denon receiver at host 192.168.0.150 could not be updated.
2017-07-02 20:15:01 ERROR (Thread-9) [DenonAVR] No mapping for source AUX1
```

Zone2 is off and not in use

Here is the XML, created from your Script:
[AppCommand_saved.zip](https://github.com/scarface-4711/denonavr/files/1117998/AppCommand_saved.zip)

The URL http://[DEVICE_IP]/goform/formiPhoneAppDirect.xml?SIAUX1 switches the AVR to AUX. 
In HA i can see that Source is AUX1, in the source select drop down i can select AUX.

After i found this out, i change the denonavr.py file SOURCE_MAPPING Section to:

```python
SOURCE_MAPPING = {"TV AUDIO": "TV", "iPod/USB": "USB/IPOD", "Bluetooth": "BT",
                  "Blu-ray": "BD", "CBL/SAT": "SAT/CBL", "NETWORK": "NET", "AUX":"AUX1"}
```
now it is working.

Do you have an idea why i need this and you not?

If you like  I can create a PR on that Topic

BR Lukas

**Comment by ol-iver** [comment]
Happy to hear that :)
I added your change to my local code ad will include that to the next version.
My receiver has AUX1 to AUX3. Yours has just one and maybe Denon renamed it in one interface but forgot to change it in the other one. Thats not the first inconsistency I noticed over the time ;)

**Comment by ol-iver** [comment]
Created a new version and a pull request at homeassistant for this.
https://github.com/home-assistant/home-assistant/pull/8409
