### ISSUE TITLE
Reading volume has stopped working on AVR-X4000

### ISSUE THREAD

**Issue by sjwright** [ol-iver/denonavr#204]
This library (as implemented in the bleeding edge dev version of HomeAssistant) has stopped being able to read the volume of my AVR-X4000. It continues to work fine with my Marantz SR6011. And it can still **modify** volume on both receivers.

I have attached the script results:
[AVR-X4000.zip](https://github.com/scarface-4711/denonavr/files/6412862/AVR-X4000.zip)

Also for the sake of helping to complete your collection, here's the SR6011 as well:
[SR6011.zip](https://github.com/scarface-4711/denonavr/files/6412870/SR6011.zip)

Thanks!

**Comment by ol-iver** [comment]
@sjwright thanks for the files. I just had a quick look and it seems that the update fails because your X4000 does not support Tone Control. That's a bug I fixed yesterday in [version 0.10.6](https://github.com/scarface-4711/denonavr/releases/tag/0.10.6)
I released a pull request too https://github.com/home-assistant/core/pull/49984. I'm not sure if it will make it to HA 2021.5 release.

**Comment by ol-iver** [comment]
The fix will be included in [HA 2021.5.1](https://github.com/home-assistant/core/milestone/400)

**Comment by sjwright** [comment]
Confirmed and working, thank you.
