### ISSUE TITLE
How to use async_setup() ?

### ISSUE THREAD

**Issue by prcutler** [ol-iver/denonavr#218]
For the application I'm working on, I want to use the async API calls.  When I call `d.async_setup()` below I'm getting an error message that it was never awaited.

What is the correct way to start an instance using the async calls?  You can see below that the setup never works in line 4 because it tries to run async_setup() again on line 5 when it does `d.async_update()`

If I can get a couple pointers, I'll update the readme with some async examples.

Thanks!

Paul

Here's some code:

```
import denonavr

d = denonavr.DenonAVR("192.168.1.119")
d.async_setup()
d.async_update()

print(d.volume)
```

It errors out with:

```
❯ python async_denonavr.py
/Users/prcutler/workspace/pi-dial/async_denonavr.py:4: RuntimeWarning: coroutine 'DenonAVR.async_setup' was never awaited
  d.async_setup()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
/Users/prcutler/workspace/pi-dial/async_denonavr.py:5: RuntimeWarning: coroutine 'DenonAVR.async_update' was never awaited
  d.async_update()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
None
```

**Comment by JPHutchins** [comment]
Hello!  Thanks for taking this on!  Try these steps:

Use python3 (>=3.8) asyncio REPL:
```
python3 -m asyncio
```

`await` your async functions to "make them synchronous":
```
import denonavr
d = denonavr.DenonAVR("192.168.1.119")
await d.async_setup()
await d.async_update()
print(d.volume)
```

Let us know if it works for you!

J.P.

**Comment by prcutler** [comment]
@JPHutchins Thank you!  I was able to get it working in the REPL.

I haven't used async & await before - now I need to go learn that so I can get this working in a .py file.

Thanks again.

--Paul

**Comment by JPHutchins** [comment]
Cool!  Async/await paradigm is awesome but definitely a deep subject that gets into threading and concurrency - it's doing all the hard stuff for us and letting us write code that looks normal (normal meaning it looks synchronous because the event loops and callbacks are hidden).  It is sorta OK for async/await to "just work"... until it doesn't.  Like if multiple "components" are "awaiting" different things.  It's a bit rigorous, but [Real Python](https://realpython.com/async-io-python/) is always great for this sort of stuff!

Great quote from the article:
"
Async IO Is Not Easy
I’ve heard it said, “Use async IO when you can; use threading when you must.” The truth is that building durable multithreaded code can be hard and error-prone. Async IO avoids some of the potential speedbumps that you might otherwise encounter with a threaded design.

But that’s not to say that async IO in Python is easy. Be warned: when you venture a bit below the surface level, async programming can be difficult too! Python’s async model is built around concepts such as callbacks, events, transports, protocols, and futures—just the terminology can be intimidating. The fact that its API has been changing continually makes it no easier.
"

Please close this issue unless you have any follow ups.

Cheers,
J.P.
