### ISSUE TITLE
M-CR510 media_player.select_source error

### ISSUE THREAD

**Issue by kiddyfurby** [ol-iver/denonavr#221]
My home assistant 2021.7.3 logged this:
```
Command async_select_source failed with error: No mapping for input source 'AUX:Digital In'
```
I used to be able to select_source in 2020, and then later on only when I specify 'AUXD' as the source, but now with HA 2021.7.3 I cannot select_source no matter I use 'AUX:Digital In' or 'AUXD'

Please use the XML dumps from my previous issue
> [M-CR510 xml.zip](https://github.com/scarface-4711/denonavr/files/6249072/M-CR510.xml.zip)

**Comment by robertbeal** [comment]
I have this receiver and this exact issue. I've started digging, still understanding the code, but one thing that stood out. The string values for the sources differ:

```
>>> d.input_func_list
['AUX:Analog In', 'AUX:Digital In', 'Favorites', 'Front USB', 'Internet Radio', 'Music Server', 'Rear USB', 'Spotify']
>>> d.input_func
'AUXD'
```
I can get it to change to some sources, the amplifier does change but it's not reflected by `denonavr`
```
>>> d.set_input_func("Spotify")
>>> d.input_func
'AUXD'
```
So possibly a mis-match for certain sources between what `denonavr` see's as the array of inputs, and what the hifi actually expects? But I've no idea why I can change source to Spotify, but it's not reflected by what source `denonar` thinks it's on (needs more digging)

**Comment by robertbeal** [comment]
Aha! Found the map of strings to Ids from `d.zones`:

```
_input_func_map={'Favorites': 'Favorites', 'Internet Radio': 'Internet Radio', 'Music Server': 'Music Server', 'Spotify': 'Spotify Connect', 'Front USB': 'USB', 'Rear USB': 'USB2', 'AUX:Digital In': 'AUX4', 'AUX:Analog In': 'AUX2'}, _input_func_map_rev={'Favorites': 'Favorites', 'Internet Radio': 'Internet Radio', 'Music Server': 'Music Server', 'Spotify Connect': 'Spotify', 'USB': 'Front USB', 'USB2': 'Rear USB', 'AUX4': 'AUX:Digital In', 'AUX2': 'AUX:Analog In'}
```
Hmmm Digital In is mapped to AUX4 (as is Rear USB). And `p.input_func` returns me AUXD

**Comment by robertbeal** [comment]
This looks like an oddity with the amp itself. It seems to return the wrong source Ids to `denonavr` as part of it's info. I'm making an assumption that it worked before because of an edge case coded into the library. 

In the case of Digital In, the amp reports it as AUX4, but actually the amp responds to AUXD when switching source

`curl "http://<ip>//goform/formiPhoneAppDirect.xml?SIAUXD"` switching source works
`curl "http://<ip>//goform/formiPhoneAppDirect.xml?SIAUX4"` switching source doesn't work

Yet in `curl "http://<ip>/goform/Deviceinfo.xml"` it lists (as a snippet):

```
                <Source>
                    <IconId>14</IconId>
                    <DefaultName>AUX:Digital In</DefaultName>
                    <FuncName>AUX4</FuncName>
                    <SourcePath>root/AUX4</SourcePath>
                    <GroupNo>2</GroupNo>
                    <RelatedFunc></RelatedFunc>
                </Source>
```

It looks like this issue has come up in the past when first adding Marantz support:
https://github.com/scarface-4711/denonavr/issues/4#issuecomment-290558871

It's covered in the test files here: https://github.com/scarface-4711/denonavr/blob/master/tests/xml/M-CR510-AppCommand-update.xml#L38

Looks like a case of grabbing the values from AppCommand

**Comment by ol-iver** [comment]
This error is hopefully fixed now.There is a Home Assistant [PR](https://github.com/home-assistant/core/pull/55805) for it. Please reopen if it is still not working after the PR was merged.
