### ISSUE TITLE
Lib seems to return MCH_STEREO when sound mode is actually set to stereo

### ISSUE THREAD

**Issue by iloveicedgreentea** [ol-iver/denonavr#227]
I am using this as part of the home assistant integration which just returns whatever this lib returns. When my 6700 is set to stereo (regular stereo, 2.1 channels being used), HA reports Multi Ch In 7.1 for raw, and MCH_STEREO for the sound mode. I am trying to piece together where this bug is coming from, but if you know already that would be helpful.

**Comment by ol-iver** [comment]
The mapping in your case looks like our [desired mapping](https://github.com/ol-iver/denonavr/blob/0a3a3d5e97e81da057030108fcc8c7f7fe8cfd99/denonavr/const.py#L109-L110)
The raw mode is the value your receiver returns before we map anything. I don't know why it reports Multi Channel 7.1 in your case. Maybe @starkillerOG knows something about it.

**Comment by starkillerOG** [comment]
@iloveicedgreentea the `sound_mode_raw` attribute (you can find it under Developer Tools --> States) in HomeAssistant represents directly what the receiver returns as the current sound mode.

Therfore if the receiver reports as the raw sound mode "Multi Ch In 7.1" that is a problem in the receiver firmware itself and we can not do anything about it. The only thing we do is map the known sound modes to a small list of sound modes that can be set.
The mapping "Multi Ch In 7.1" --> MCH_STEREO seems a bit odd since Multi Ch In 7.1 sounds more like a surround output format, but I would need to get more information about what the receiver was actually playing for source material and what the output sound mode actually was.

**Comment by iloveicedgreentea** [comment]
Thanks for looking into it, that makes sense. I would definitely believe its a bug in their firmware. I have not noticed this happen again with stereo sources, so I suspect it was some weird interaction between the firmware and some specific source. If sound_mode_raw is pulled from the receiver itself, then I don't think there is any bug with this lib 🥇
