### ISSUE TITLE
Not able to match sound mode 'DOLBY DIGITAL + + NEURAL:X'

### ISSUE THREAD

**Issue by HVR88** [ol-iver/denonavr#231]
**AVR model:**
 Marantz AV7703

**From Home Assistant's Developer state inspector:**
sound_mode: DOLBY DIGITAL +   + NEURAL:X
sound_mode_raw: Dolby Digital +   + Neural:X

**From the HA log:**
Logger: denonavr.soundmode
Source: /usr/local/lib/python3.9/site-packages/denonavr/soundmode.py:162
First occurred: 7:56:32 PM (1 occurrences)
Last logged: 7:56:32 PM

Not able to match sound mode: 'DOLBY DIGITAL + + NEURAL:X', returning raw sound mode.

**Comment by ol-iver** [comment]
I'm sorry, I cannot reproduce this error. This sound mode [is existing](https://github.com/ol-iver/denonavr/blob/a0422866794e0fc3c1e476fc44dd8b0a2f1bc236/denonavr/const.py#L92).
@starkillerOG any ideas?

**Comment by HVR88** [comment]
Is it affecting all modes with a colon in the name? I have a vague recollection it also produced a warning on another Neural mode, but I'll have to play with the modes to verify.

**Comment by ol-iver** [comment]
When does the error occur? Is it when home-assistant is starting up or when you change sound mode while it is running?
I don't think the colon is the reason for this.

**Comment by HVR88** [comment]
While HA is already running, playing surround content through the AVR causes the AVR to detect the soundmode and the integration to log the warning. 

**It seems to do this only the first time the sound mode is activated.**

If I try to manually switch modes after it has already logged the warning, it won't cause a second warning when cycling back to the Neural:X mode.

If I exit playback, which sets the AVR back to stereo, and then restart playback, it also doesn't trigger a second warning.

**Comment by ol-iver** [comment]
This kind of warning only occurs once per non recognized sound mode, because then the new sound mode is cached. However, it is not mapped to the right group and you are not able to set it in Home-Assistant.

Could you please switch your receiver to Neural:X mode and run the python script you find [here](https://github.com/ol-iver/misc_python_tools/tree/master/denonavr)? It saves the responses of your receiver into xml files of the directory you start it from.
If you will zip and upload these xml files here, I might find a solution.

**Comment by HVR88** [comment]
I'll give this a try and report back later tonight.

**Comment by HVR88** [comment]
Here are the three files that generated content. All others were 403 - access forbidden.

[AV7703-neuralx.zip](https://github.com/ol-iver/denonavr/files/8526387/AV7703-neuralx.zip)

**Comment by ol-iver** [comment]
Thanks, that's fine. There are a couple of endpoints which return the same data in different formats. Different types of receivers support different endpoints. That's why the whole thing is complex.

I found the issue. There are more spaces in your soundmode than the one currently saved in the library.
`"DOLBY DIGITAL + + NEURAL:X"` (library with 1 space between + and +)
`"DOLBY DIGITAL +   + NEURAL:X"` (yours with 3 spaces between + and +)

The funny thing is that the spaces are removed by github even when formatting it as code 😅 
I'll add your entry and create a new version.

**Comment by HVR88** [comment]
Normalizing/sanitizing the data by removing all white space from the string first before any comparisons will catch this and any other variations that might be out there. 😀

**Comment by ol-iver** [comment]
Good idea 😄 
Strings have been converted to upper case already. However, removing all whitespaces makes things hard to read, so multiple spaces are removed now.

**Comment by ol-iver** [comment]
I created PR https://github.com/home-assistant/core/pull/70450 to include the new package version there.

**Comment by HVR88** [comment]
Thanks for your attention and fix.

**Comment by starkillerOG** [comment]
> I'm sorry, I cannot reproduce this error. This sound mode [is existing](https://github.com/ol-iver/denonavr/blob/a0422866794e0fc3c1e476fc44dd8b0a2f1bc236/denonavr/const.py#L92). @starkillerOG any ideas?

Sorry for taking so long to respond, have been a bit bussy.
Yhea I was already guessing it would be spaces but when I counted in github the number of spaces was correct.
That's really annoying that github removes the spaces, good catch @ol-iver!

Greath work on the improvements @ol-iver!
