### ISSUE TITLE
async_verify_avr_2016_update_method is unexpectedly expensive

### ISSUE THREAD

**Issue by bdraco** [ol-iver/denonavr#233]
Based on the name, I'm not 100% if its supposed to run every update or just once to verify the method is there
<img width="1326" alt="Screen_Shot_2022-04-26_at_13_48_53" src="https://user-images.githubusercontent.com/663432/165410926-e3a5af95-e99d-48d7-8268-1cbde4727f15.png">

**Comment by ol-iver** [comment]
It turned out some receivers are changing their port from 80 to 8080 while they are running. `async_verify_avr_2016_update_method` tries to detect that and set it up on the new port. This could happen anytime.
The major part of `async_verify_avr_2016_update_method` is `async_get_global_appcommand` which is the query getting updates from the receiver. The later method has to run on each update and its result is cached for the subsequent methods. Thus, in the end it has only sort of a "reading from dictionary" impact.

**Comment by bdraco** [comment]
Is is possible to rework it so it trapping the failure and switching ports instead of doing the verify first?

**Comment by ol-iver** [comment]
Why? 99.9% of the verify step is the query to the receiver. On success the result is cached and is used to update the properties. It has no impact on the processing time. When you remove the verify step, the same query will be performed in the next step of the update, because the cache would be empty.

**Comment by bdraco** [comment]
> Why? 99.9% of the verify step is the query to the receiver. On success the result is cached and is used to update the properties. It has no impact on the processing time. When you remove the verify step, the same query will be performed in the next step of the update, because the cache would be empty.

I didn't realize the data was actually used. 🙈.

I don't think there is anything to be done here to improve the performance here

**Comment by bdraco** [comment]
Thanks for looking!
