### ISSUE TITLE
Add support for older Denon AVRs by making STATUS_URL configurable

### ISSUE THREAD

**Issue by sebk-666** [ol-iver/denonavr#28]
Hi,

I have an older AVR-4810 which apparently only has a subset of the current web interface structure.
For example, it's missing the "`/goform/formMainZone_MainZoneXmlStatus.xml`" page which is kind of essential to denonavr.
However, I realized that I could just set 
`STATUS_URL = "/goform/formMainZone_MainZoneXml.xml"`(i.e. to the same value as `MAINZONE_URL`)
to get denonavr working in large parts (I'm using it within home-assistant).

If `STATUS_URL` could be user-configurable (or maybe just be set to `MAINZONE_URL` in case `/goform/formMainZone_MainZoneXmlStatus.xml` returns a 404), that would be really great.

I'd be happy to assist with further information, e.g. a dump of the formMainZone_MainZoneXml.xml file from my AVR.

Sebastian

**Comment by ol-iver** [comment]
@sebk-666, sorry I could not spend much time on this the last weeks, but I'll try to figure out, how I can solve your issue.
A configurable status url would not be useful, because the different urls behave somehow differently even if they are looking more or less the same. That would be pretty intransparent for most of the home assistant users.
I'll try to fix the issue for your receiver, if you could send me some test files. I prepared a little python script, which gets all different XMLs the library is using and saves them to the directory from which it was started.
[denon_receiver_xml.zip](https://github.com/scarface-4711/denonavr/files/1385456/denon_receiver_xml.zip)
You could run it like this ```python denon_receiver_xml.py --host 192.168.x.y. --prefix AVR-4810```

Cheers,
Oliver

**Comment by sebk-666** [comment]
Thanks for looking into this!
I have attached a zip file with the xml files produced by the script.

[denon_avr_4810.zip](https://github.com/scarface-4711/denonavr/files/1385584/denon_avr_4810.zip)

Sebastian

**Comment by ol-iver** [comment]
Got it 👍 
I just did the changes and added the new version to a [pull request in home-assistant](https://github.com/home-assistant/home-assistant/pull/9887).
I will close this issue. If the changes are not working for you, please reopen it.
