### ISSUE TITLE
Song album, artist title from AirPlay?

### ISSUE THREAD

**Issue by brookstalley** [ol-iver/denonavr#45]
I'm about to invest an an AVR-X4400 and this project looks like the most likely way to integrate it into my system in place of the Yamaha RX-A750 I'm using today.

It's critical that my overall system be able to retrieve the currently playing media when AirPlay is the source... can someone please kindly confirm that this should work? I did see the issue about changes to the interface on the AVR-X series, but it wasn't clear if that impact song metadata.

Thanks!

**Comment by ol-iver** [comment]
@brookstalley unfortunately the song meta data are affected by the change. 
The current status is:
- The interface of pre 2016 AVR-X devices supports song metadata
- 2016 and later AVR-X devices does not support them

I assume the AVR-X4400 is a new device, so it won't show song metadata. Maybe there is a solution for it, but I can't figure it out by myself, because I do not own a receiver from 2016 and later.
