### ISSUE TITLE
No connection to /goform/AppCommand.xml

### ISSUE THREAD

**Issue by cihanulusoy** [ol-iver/denonavr#46]
Hi,

I'm running HA 0.69.1 on a Raspberry Pi 3 B+ in a Python 3.5 virtual environment. I was using denonavr with marantz SR6007 without any issues till 0.68.? and possibly before the code was pushed to 0.7.0.

Yesterday, I've changed the code to accommodate with the unavailable sources after noticing https://github.com/scarface-4711/denonavr/issues/36 and got rid of the "no mapping for source " errors. However, I am still getting the following errors:

No connection to /goform/AppCommand.xml end point on host 192.168.0.3
Getting renamed and deleted sources failed.
Receiver sources list empty. Please check if device is powered on.

Modified code is:

`SOURCE_MAPPING = {"TV AUDIO": "TV", "iPod/USB": "USB/IPOD", "Bluetooth": "BT",
                  "Blu-ray": "BD", "CBL/SAT": "SAT/CBL", "NETWORK": "NET",
                  "Media Player": "MPLAY", "AUX": "AUX1", "Tuner": "TUNER",
                  "CD": "CD", "DVD": "DVD", "VCR": "VCR", "GAME": "GAME"}`

I'm also experiencing difficulties in connecting to the marantz SR6007 through the Remote app. The remote app either finds the IP or name and IP together but doesn't connect.

Could you please help?

Thanks in advance.

**Comment by ol-iver** [comment]
@cihanulusoy version 0.7.0 should not be the reason for your connection issue, because it is not used in HA yet. When you look at the pull request history of the [https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/media_player/denonavr.py](HA component) you see that it is on 0.6.1 since HA version 0.64.1.
You mentioned that there are some connection issues using the receiver's remote app. Thus, I assume this is the reason for you HA connection issue too. 

I will add the **"Tuner": "TUNER"** part of your changes to the next version. The other entries are not neccessary. The way it is implemented you only need to create an entry in the SOURCE_MAPPING dictionary in case the value is different than the key.

**Comment by cihanulusoy** [comment]
Thanks for your response.

**Comment by ol-iver** [comment]
Just included the changes with your SOURCE_MAPPING entry to [HA pull request](https://github.com/home-assistant/home-assistant/pull/14551).
Closing this issue. If the change is not working please re-open it.

**Comment by Verguldebarman** [comment]
Just upgraded to 2020-12 and see this error (again):

```
Logger: Audyssey
Source: /usr/local/lib/python3.8/site-packages/denonavr/audyssey.py:62
First occurred: 10:49:47 (41 occurrences)
Last logged: 14:46:23

No connection to /goform/AppCommand0300.xml end point on host 192.168.0.113
```
