### ISSUE TITLE
Marantz SR7013

### ISSUE THREAD

**Issue by skynetforcats** [ol-iver/denonavr#77]
Hi
This project was working for my Marantz SR7010 in home assistant, but not with my new SR7013:
"returned HTTP status code 403"
and
"End point /goform/AppCommand.xml on host [ip address] returned malformed XML."

**Comment by sebk-666** [comment]
Same here for my Denon X8500H. 
There's a completely new web interface on port 10080 - connecting on port 80 redirects there.
After also specifying the port with the host ip address, Home-Assistant throws these messages with `debug` log level:

```
2019-04-10 10:21:58 INFO (SyncWorker_7) [DenonAVR] Identified receiver type: 'avr' on port: '80'
2019-04-10 10:21:58 ERROR (SyncWorker_7) [DenonAVR] No connection to /goform/AppCommand.xml end point on host 192.168.10.35:10800
2019-04-10 10:21:58 ERROR (SyncWorker_7) [DenonAVR] Getting renamed and deleted sources failed.
2019-04-10 10:21:58 ERROR (SyncWorker_7) [DenonAVR] Receiver sources list empty. Please check if device is powered on.
2019-04-10 10:21:58 ERROR (SyncWorker_7) [DenonAVR] Missing status information from XML of Main for: Power, InputFuncSelect, Mute, MasterVolume
```

Looks to me like a major update to the library is needed in order to work with the new web interface.

Sebastian

**Comment by tomdh76** [comment]
Marantz SR7011 also not working with a 403 access. I can use http on port 8080 but the denonavr component probably does not use port 8080 for the SR7011 port. I also do not know how to edit the denonavr py because I use docker and cannot find the py file. @scarface-4711: would it be possible to include the SR7011 in the py?

**Comment by alaksandus** [comment]
Somebody seems to have found a workaround: https://github.com/home-assistant/home-assistant/issues/22102

> Doesn't look directly related to HA (rather it's a dependency issue). The bump to 0.7.9 of `denonavr` seems to be the issue.
> 
> I've not looked at that package in detail, but there were recent commits (as part of 0.7.9) around model names:
> [scarface-4711/denonavr@a2e5483](https://github.com/scarface-4711/denonavr/commit/a2e5483f622d05ed3c3bead14db39b1826384425)
> 
> In the short term a revert to 0.7.8 should fix the issue while the `denonavr` package is patched and new version released.

**Comment by skynetforcats** [comment]
I made it work on my SR7013 by adding the Marantz SR70xx model numbers to the list.

``
DEVICEINFO_AVR_X_PATTERN = re.compile(
    r"(.*AVR-(X|S).*|.*SR500[6-9]|.*SR60(07|08|09|10|11|12|13)|.*SR70(07|08|09|10|11|12|13)|.*NR1604)")
``

Could this please be implemented?

**Comment by ol-iver** [comment]
@ACrazyConcept I'll include this into the next version

@sebk-666 It is probably too difficult for me to rework the library without having access to real device

**Comment by ol-iver** [comment]
Added the changes to the library and home-assistant https://github.com/home-assistant/home-assistant/pull/30421

**Comment by skynetforcats** [comment]
Just now updated and my SR7013 seems to be working in HA as expected. Thanks!
