### ISSUE TITLE
Zone 2 Power and Input

### ISSUE THREAD

**Issue by JoeSzymkowicz** [ol-iver/denonavr#8]
I see the code only references control of the Main Zone, though some of the supported models support Zone 2. Are there any plans to add controls for Zone 2? Power toggle? Input selection? Volume control?

**Comment by ol-iver** [comment]
hey Joe,
this topic was on my list. I got somehow frustrated because about inconsistant variables accross the different interfaces. The others zones should not be too different from the main zone, so I could realize that when I'm back from vacation in about two weeks.
If you like, I let you know, when there is a first version to test.
Btw. which Denon model are you using?

**Comment by JoeSzymkowicz** [comment]
I have an AVR-X2000. Yes, please let me know, I would gladly test anything you can work on. In the meantime, I thought I would reference a issue that I created in the HASS forum; https://github.com/home-assistant/home-assistant/issues/7486
This component was working well in a previous installation that I had on a Windows box just before I shifted over to running HASS on an RPI.

**Comment by ol-iver** [comment]
Probably I created that issue on the last version of the library. But I might have an idea about it. Could you please run the python file in the attached zip like this:
`python denon_appcommand_output.py --host 192.168.0.250`
It will created a file AppCommand_saved.xml in the same directory, which you could upload here please
[denon_appcommand_output.zip](https://github.com/scarface-4711/denonavr/files/983101/denon_appcommand_output.zip)

Additionally I would be interested in the following xmls of your receiver for testing purposes, but the output of the python file is the most important one.
_http://**[IP of your device]**/goform/Deviceinfo.xml
http://**[IP of your device]**/goform/formMainZone_MainZoneXmlStatus.xml
http://**[IP of your device]**/goform/formMainZone_MainZoneXml.xml
http://**[IP of your device]**/goform/formNetAudio_StatusXml.xml_

**Comment by ol-iver** [comment]
Just checked your issue in the home-assistant repository and the error log you attached seems to be somehow incomplete at the end. Could you check please?

**Comment by bieniu** [comment]
Hi. I have Denon AVR-X2100W with two zones and this is zip with all xml files https://bieniu.eu/fbsharing/koJWGwdk

**Comment by ol-iver** [comment]
cool, thanks for the files @bieniu . You are not getting the error Joe posted for homeassistant 0.44 right?
At least I was able to start it on my PC with your example files.

**Comment by bieniu** [comment]
No, I don't have any DenonAVR errors after upgrade to 0.44.

**Comment by JoeSzymkowicz** [comment]
I have zipped the requested XMLs. I have an AVR-X2000.
https://drive.google.com/file/d/0BwT5qUgj8wyTMkpwWUxWYnp3TEk/view?usp=sharing

Tried running that script you include earlier:
Traceback (most recent call last):
  File "denon_appcommand_output.py", line 5, in <module>
    import requests
ImportError: No module named requests
Seems odd because I have requests installed.
"pip install requests"
Requirement already satisfied: requests in /usr/lib/python3/dist-packages

EDIT: I'm failing at buttons at the moment, please ignore close and reopen.

**Comment by JoeSzymkowicz** [comment]
``

**Comment by ol-iver** [comment]
hey guys,
almost ready to start with the multiple zone upgrade ;)
It would be great, if you could send me some example files again, because I have no speakers at my Zone2 and Zone3. I created an enhanced version of the script which saves all files that I'll probably need.
[denon_receiver_xml.zip](https://github.com/scarface-4711/denonavr/files/1032430/denon_receiver_xml.zip)
`python denon_receiver_xml.py --host 192.168.0.250 --prefix AVR-X4100W`
The prefix is for the filenames saved with the current run.
It would be great, if you could get different scenarios like...Main Zone using DVD input while Zone2 is playing some track from the media server etc...

@JoeSzymkowicz: Somehow strange that error...but I have an idea ;)
Assuming you did not start the script from a virtual env maybe calling _python..._ is pointing to a different version than _pip..._ 
If it also happens with the new script simply call it using
`python3 denon_receiver_xml.py --host 192.168.0.250 --prefix AVR-X4100W`
How could this happen? Ubuntu 16.04 and also Debian Jessie is using python 2.7 as default, but also optional 3.4 (3.5). If you install pip for python3 and do something like _sudo pip3 install --upgrade pip_ it creates a link from pip to pip3, but starting _python_ still runs python 2.7

**Comment by p3dda** [comment]
Hi,

great to hear you making progress on this topic.

I have attached the requested files for my Marantz NR1604 (which seems as many Marantz devices to be identical to Denon concerning XML API). Main Zone is streaming Web Radio, while Zone2 is using CD.
[NR1604-XML.zip](https://github.com/scarface-4711/denonavr/files/1032682/NR1604-XML.zip)

**Comment by bieniu** [comment]
I hope this helps. [Denon AVR-X2100W](https://bieniu.eu/fbsharing/9PYbXjFq)

**Comment by JoeSzymkowicz** [comment]
@scarface-4711 
The update you wrote that was implemented in HASS .45 fixed my issue and everything is working with `denonavr`. You are correct; I am not running HASS in a venv.  Here is output from `pip --version`
pip 9.0.1 from /usr/local/lib/python3.4/dist-packages (python 3.4)
 
I have generated the output of your script with both zones on, though I do not have Zone 2 connected to a media center.
https://drive.google.com/file/d/0BwT5qUgj8wyTSzREaDl4V3E0ZEU/view?usp=sharing

**Comment by ol-iver** [comment]
hej guys,
checked in a first version which supports Zone2 & Zone3 of the receivers. I would be happy if you could test the last sources from GIT before I create a new version. Some parts of the Main Zone are redesigned, so you could have a look at it too.
I did not spend to much time on documentation and testing with different models so far, but I like to  explain briefly how you could test with  this code example.
```python
import denonavr
zones = {"Zone2": "Name of Zone2", "Zone3": "Name of Zone 3"}
d = denonavr.DenonAVR("192.168.0.250", name="Name of Main Zone", add_zones=zones)
d.zones
{'Zone2': <denonavr.denonavr.DenonAVRZones object at 0x000001F893EB7630>, 'Main': <denonavr.denonavr.DenonAVR object at 0x000001F8964155F8>, 'Zone3': <denonavr.denonavr.DenonAVRZones object at 0x000001F896415320>}
d.zones['Zone2'].power
'OFF'
d.zones['Zone2'].power_on()
True
d.zones['Zone2'].update()
True
d.zones['Zone2'].power
'ON'
d.zones['Zone2'].power_off()
True
d.zones['Zone2'].update()
True
d.zones['Zone2'].power
'OFF'
```
As you can see you should assign a dictionary with keys **Zone2** and/or **Zone3** to the add_zones parameter when you create the main instance of the receiver.
The Main Zone could be used as before. Additionally you find the instances of all zones in the **d.zones** dictionary. In the example you see how the attributes and methods of the Zone instances could be accessed.
I would appreciate any feedback :)

**Comment by JoeSzymkowicz** [comment]
The new version and commands you listed worked as expected. I then tried some of the additional known commands, and they too worked as expected also.
```
d.zones['Zone2'].volume
-27.0
d.zones['Zone2'].set_volume(-25.0)
True
d.zones['Zone2'].set_volume(-27.0)
True
d.zones['Zone2'].input_func
'CCAUX'
```

I want to note that when I tried the following, it returned all the available inputs, rather than only the inputs that will work with Zone2.
```
d.zones['Zone2'].input_func_list
['AUX', 'CCAUX', 'Chromecast', 'DVD', 'Favorite Station1', 'Favorite Station2', 'Favorite Station3', 'Favorites', 'Flickr', 'GAME', 'HTPC', 'Internet Radio', 'Media Server', 'NETWORK', 'Pandora', 'ROKU', 'SiriusXM', 'Spotify', 'TUNER', 'TV AUDIO', 'iPod/USB']
```

Trying to set the zone to an input that is not compatible does nothing, so no harm no foul. Keep up the great work @scarface-4711 and can't wait until these changes roll into HomeAssistant.

**Comment by ol-iver** [comment]
Happy to hear that :)
For Zone 2 and 3 I simply referenced to the inputs of the Main zone. At my AVR-X4100w I am able to use exactly the same inputs for Zone 2 and 3 as for Main zone. That's why I created the reference. 
But my other Zones are not configured, so maybe I missed something. Could you give me examples of inputs from your receiver which are available in Main Zone but not in Zone 2 or the other way round? Maybe I could figure that out from your files then.

**Comment by JoeSzymkowicz** [comment]
Sorry about that. I checked the web ui and it does display all the available inputs in Zone2, even those not available to be used. There is nowhere in the XMLs that you can key off of to discern this. It's not a problem to just display all inputs.

I remember getting the receiver, thinking that I could play ANY input on Zone2, and being horribly bummed that only CERTAIN inputs worked on it. Denon does not make this very clear in any of the description or features of this model. The secondary purpose of the receiver is to use it for music to my outdoor deck and patio, controlled by some kind of app or webui. I've since settled with a Chromecast audio, as it's an analog stereo plug-to-RCA input and I can control it on my phone. Thank you for all your hard work. I will close this issue now. I wasn't sure how else to contact you to submit a feature request.

Citation: http://s3.amazonaws.com/szmanuals/f44c6f688cdb0acdd06803ff4a62858d, p 117
"In ZONE2, you can select iPod/USB, TUNER, NETWORK or an input source with an analog audio input connector."

**Comment by ol-iver** [comment]
Lucky you having an outdoor deck ;)
You're welcome. I had the zone support on my list, but never really started, because I'm not using it. Thus your request was a good opportunity to get this done. In the end it was easier than expected.
I just finished the work here and included the new version into home assistant. Maybe it coming with the next release. https://github.com/home-assistant/home-assistant/pull/8025

**Comment by JoeSzymkowicz** [comment]
@scarface-4711 was the update for Zone2 and Zone3 support not merged into homeassistant .47?
