### ISSUE TITLE
Denon AVR 3310 controls not working

### ISSUE THREAD

**Issue by jamaical82** [ol-iver/denonavr#96]
Hi gentlemen,

I have an old (but still good) denon avr 3310, succesfully imported in home assistant.
Unfortunately I can’t control it. I can see status, input, volume level and everything, but if I try to use controls nothing happend. What i'm doing wrong? Hope you can help me becouse is driving me crazy :) 

Thanks

**Comment by JPHutchins** [comment]
To clarify, the denon component is accurately updating its state according to changes you’ve made manually (or with the remote), like volume?  Is there another control system on the network issuing IP or telnet commands to the receiver?

**Comment by jamaical82** [comment]
Hi! The denon component let me see all the avr changes made from remote or manually. There are no other component in my network that work or communicate with it.

**Comment by jamaical82** [comment]
little update... I changed my config with the denon component instead of the denon avr component and now seems to work

**Comment by JPHutchins** [comment]
The denon component uses telnet instead of http and if it is working for you may be a good compromise.  If you need further functionality you can use the Denon telnet manual to issue generic telnet command from Home Assistant.  My only thought re denonavr is that the outgoing port isn’t correct somehow, maybe someone with an older receiver knows more.
