### ISSUE TITLE
Selecting "FM" (Tuner) Source on an AVR-2313

### ISSUE THREAD

**Issue by AvesNZ** [ol-iver/denonavr#98]
Hi, hoping you can help. I'm using Home Assistant's denonavr: component and I can switch to various sources using media_player.select_source but I can't switch to the Tuner or FM mode. More complete information is here: [https://community.home-assistant.io/t/controlling-a-denon-avr/98763](url)

Regards,
Aves

**Comment by AvesNZ** [comment]
I got some traffic sniffing going on Hyper-V and found the following which suggests it's sending the "FM" command. I'll sniff the AVR web page too and see if there's a different command that that sends.

Works as expected:
[Full request URI: http://192.168.7.10/goform/formiPhoneAppDirect.xml?SIDVD]
[Full request URI: http://192.168.7.10/goform/formiPhoneAppDirect.xml?SIGAME]

Doesn't have an effect:
[Full request URI: http://192.168.7.10/goform/formiPhoneAppDirect.xml?SIFM]

**Comment by JPHutchins** [comment]
Hello!
It looks like you are going to sniff the command coming from the app/website which will ultimately yield a solution, thanks for taking that step!  

Or you can go ahead and POST http://192.168.7.10/goform/formiPhoneAppDirect.xml?SITUNER as a sanity check and see if it switches your device:

`curl -X POST http://192.168.7.10/goform/formiPhoneAppDirect.xml?SITUNER`

In order to help solve this for future users, please try this:

`pip install denonavr` if you have not already
Then, from interactive Python shell:
`import denonavr`
`d = denonavr.DenonAVR("192.168.7.10")` I believe I have copied the IP of your AVR
`d.update()`
Then let us know the output of the following:
`d.input_func_list`
As well as:
`d.receiver_type`

**Comment by AvesNZ** [comment]
Sorry about the delay, been very busy!

I'm running Home Assistant in a Hass.io instance so have limited visibility and control of it in its container (and honestly, limited Linux knowledge!)

Seems there's a port of curl in Windows. All I get back is "curl: (52) Empty reply from server"

I'll try and sniff the traffic from a Chrome browser accessing the Denon and see if I can spot the instructions telling it to switch to the Tuner.

**Comment by AvesNZ** [comment]
Ok, here's some captures of instructions from a browser:

Switching to Media Player:
![image](https://user-images.githubusercontent.com/55373387/66087693-e9cf1180-e5d4-11e9-9145-029c820e1569.png)

Switching to FM (Tuner):
![image](https://user-images.githubusercontent.com/55373387/66087707-f6536a00-e5d4-11e9-9340-33759bfb79c3.png)

I'll look at how I might generate the POST command you suggested above.

**Comment by JPHutchins** [comment]
It looks like we do not implement that API (not to say that it is impossible) someone else might know more.  Most of the commands seem to originate from mobile applications.  From Windows you can test the POST command given above using the free software Postman: https://www.getpostman.com/

Or from a Linux VM use terminal to issue the command: 
`curl -X POST http://192.168.7.10/goform/formiPhoneAppDirect.xml?SITUNER`

**Comment by AvesNZ** [comment]
Yes, the browser does seem to do it a totally different way.
I wonder if I can get a mobile application that supports it and sniff THAT traffic... I'll check out the app store.

**Comment by JPHutchins** [comment]
This document contains a guide to sniff the app traffic.  Though I really do think that the command we need to alter is the POST command mentioned above.

https://github.com/scarface-4711/denonavr/blob/master/doc/XML_data_dump.txt
